#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

// Data feeding
$family = new Family();
$shan = new Member("King Shan", "M");
$shan->addSpouse("Queen Anga");
$family->addMember($shan);

$application->add(new MeetTheFamilyCommand($family));

$application->run();