#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/init.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new FeedFamilyCommand());
$application->add(new MeetTheFamilyCommand());
$application->add(new AddChildCommand());

$application->run();