#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

function dd($m){
	dump($m);
}

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new MeetTheFamilyCommand());

$application->run();